### PR TITLE
Remove patches to access library

### PR DESCRIPTION
**Pull request by PuercoPop**
The patches where merged upstream. https://github.com/AccelerationNet/access/pull/7

Just in case run the test suite locally before merging. Also, maybe the removal should wait until the next release of quicklisp when the upstream merges are released?

### CODE REVIEW

**Comment by mmontone** [comment]
This is great work! Thank you!

I don't know if I should wait for Quicklisp dist or not. It's been quite a long time since the last dist update, I think.

**Comment by jorams** [comment]
If the changes have been merged into Access, I think you should merge right now. That'd mean both libraries are updated in the same dist.

**Comment by mmontone** [comment]
@PuercoPop  Haha. I'm getting your heap exhaustion error when testing this PR.

**Comment by mmontone** [comment]
Something is looping when I run the tests

**Comment by mmontone** [comment]
Ok. I've fixed that. Tests pass.

**Comment by PuercoPop** [comment]
> Something is looping

After reading the token parser, I think we should say something is recurring instead :smile: The original author is clearly a Schemer at heart.

But really, thank you for all the work you've done to document, reorganize and improve the code base and made it more understandable. A lion's share of work.

**Pull request merged**
