### PR TITLE
truncatechars filter should count the ellipsis

### PR DESCRIPTION
**Pull request by PuercoPop**
The documentation and the implementation disagreed, I went with the documentation as it made more sense to me.

### CODE REVIEW

**Comment by PuercoPop** [comment]
Btw I forget to ask, do what do you mean by adopting interactive? Do you want to add an interactive restart to parse-integer?

**Comment by jorams** [comment]
The documentation for `truncatechars` says the following:

> Truncated strings will end with a translatable ellipsis sequence (”...”).

I haven't looked into the code enough to check if the "..." can actually be translated to other languages, (a quick glance suggests it can not, meaning the documentation is incorrect) but that could invalidate the assumption for the replacement to actually be 3 characters wide. That would mean *not* counting those characters would make more sense.

(I wonder if it would be a good idea to use an actual ellipsis character (`&hellip`) as the (default) character to indicate truncation.)

**Comment by PuercoPop** [comment]
There is a bug in this PR, if doesn't handle truncation values less than 3.

I think @jorams is on to something with the problems with handling translation. Maybe adding a ellision-indication keyword argument would be a good idea

**Comment by PuercoPop** [comment]
Bugfix pushed.

Also I added an optional parameter ellision-string to allow the user to override the default as per @jorams suggestion. However I'm unsure as to what is the syntax to pass optional parameter in a template. This doesn't seem to work

```lisp
(let ((template (compile-string "{{ foo|truncatechars:5 'xx'}}")))
  (render-template* template cl:*standard-output* :foo "haihai"))
```

I looked at the documentation for example of optional parameters but found none. [Urlencode](http://mmontone.github.io/djula/doc/build/html/filters.html#urlencode) says it takes an optional parameter but it [does not appear to be the case](https://github.com/mmontone/djula/blob/master/src/filters.lisp#L166)

**Comment by jorams** [comment]
@PuercoPop I interpreted "translatable" to mean the default translation system could be used to translate the string, not that there would be an extra parameter.

**Comment by mmontone** [comment]
When testing this, I'm getting errors when running the tests:
```
{# Error: There was an error running filter TRUNCATECHARS : The variable DJULA::ELLISION-STRING is unbound. #}
   [Condition of type DJULA::TEMPLATE-ERROR]
```

And when I look in filters.lisp, there are compilation errors: 
```
; No value
;     (CONCATENATE 'STRING
;                  (SUBSEQ DJULA::IT-STRING 0
;                          (- DJULA::N DJULA::ELLISION-STRING-LENGTH))
;                  DJULA::ELLISION-STRING)
; 
; caught WARNING:
;   undefined variable: ELLISION-STRING

;     (COND
;      ((> DJULA::ELLISION-STRING-LENGTH DJULA::IT-STRING-LENGTH)
;       (DJULA::TEMPLATE-ERROR
;        "filter truncatechars: The ellision-string is is larger than the maximum length."))
;      ((> DJULA::IT-STRING-LENGTH DJULA::N)
;       (CONCATENATE 'STRING
;                    (SUBSEQ DJULA::IT-STRING 0
;                            (- DJULA::N DJULA::ELLISION-STRING-LENGTH))
;                    DJULA::ELLISION-STRING))
;      (T STRING))
; --> IF COND IF COND THE 
; ==>
;   (PROGN STRING)
; 
; caught WARNING:
;   undefined variable: STRING
; 
; compilation unit finished
;   Undefined variables:
;     ELLISION-STRING STRING
;   caught 2 WARNING conditions
```

These are the commits I'm testing:

```
09f14dd * PuercoPop-truncatechars Make elision-string a global variable
2581e17 * truncatechars filters bugfix
1534aaf * truncatechars filter should count the ellipsis
06de519 *   origin/master origin/HEAD master Merge pull request #17 from PuercoPop/error-template
```

**Comment by PuercoPop** [comment]
Ups, I didn't test the last commit, making elision string a global so I forgot the earmuffs and updating the test case. I'll fix it. The other commits did pass the tests.

**Comment by PuercoPop** [comment]
@mmontone Can you test the last commit again? I've fixed and rebased it.

**Comment by mmontone** [comment]
@PuercoPop  I may have screwed up with the merge. Sorry. Can you check?

**Comment by PuercoPop** [comment]
Everything seems fine in the current master.

**Comment by mmontone** [comment]
Cool!

**Comment by PuercoPop** [comment]
Btw, I'm still unclear as to how optional parameters work in filters and what is the interactive todo note

**Comment by mmontone** [comment]
Ok. Let me have a look. Regarding docs, I actually stole lots of docs from Django templates as I didn't want to write everything from scratch, so it is not reliable everywhere.

**Comment by mmontone** [comment]
@PuercoPop  I didn't write the interactive TODO note, and I don't know what it means. I'm not the original author of the library.

**Comment by mmontone** [comment]
@PuercoPop As for the optional arguments in filters. You tried something like: 

```
(def-filter :truncatechars (it n &optional ellipsis)
```

but it didn't work?

**Comment by PuercoPop** [comment]
It did work for when calling the function directly. What I'm unsure of is how pass it from the template. Is it

```
{% foo | truncatechars: 5 xx %}
```
?

**Comment by PuercoPop** [comment]
Regarding the interactive note, my best guess is that he meant something like what [StumpWM](https://github.com/stumpwm/stumpwm/blob/master/command.lisp) with the interactive args of defcommand and define-stumpwm-type (Which is CLIM inspired). That would allow having arguments beside strings and better error reporting. Although that note would apply to more than that specific filter in that case

**Comment by PuercoPop** [comment]
Apparently [here](https://github.com/mmontone/djula/blob/master/src/variables.lisp#L6) is where the optional arguments could be handled by spiting the string after the colon on spaces. However for proper error reporting the number of arguments has to be compared to the filter function lambda list. A possible future enhancement?

**Comment by mmontone** [comment]
On 15/09/15 13:05, Javier Olaechea wrote:
> Apparently here
> <https://github.com/mmontone/djula/blob/master/src/variables.lisp#L6> is
> where the optional arguments could be handled by spiting the string
> after the colon on spaces. However for proper error reporting the number
> of arguments has to be compared to the filter function lambda list. A
> possible future enhancement?

Yep...

**Pull request merged**
